import Layout from "@components/Layout";
import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {

  return (
    <Layout>
      <div className={styles.container}>
        <Head>
          <title>Elite App</title>
          <meta name="description" content="generated by elite team" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main>
          <h1>Main goes here</h1>
        </main>

        <footer className={styles.footer}>
        </footer>
      </div>
    </Layout>
  );
};

export default Home;
